// lib/services/limits.ts

export const LIMITS = {
  MAX_TEACHERS: 5,
  MAX_QUIZZES_PER_TEACHER: 1,
  MAX_QUESTIONS_PER_QUIZ: 50,
  MAX_QCM_QUESTIONS: 40,
  MAX_DEVELOPMENT_QUESTIONS: 10,
  MAX_STUDENTS_PER_QUIZ: 60,
  ACCOUNT_DURATION_DAYS: 3,
};