import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

import type {
  Quiz,
} from "@/lib/services/quizzes";

import type {
  Attempt,
  AttemptAnswer,
} from "@/lib/services/attempts";

import type {
  Question,
} from "@/lib/services/questions";

/* =========================================================
   Types
   ========================================================= */

export type PdfLanguage =
  | "en"
  | "fr"
  | "rn";

type AttemptCorrectionPdfProps = {
  quiz: Quiz;

  attempt: Attempt;

  questions:
    Question[];

  language?:
    PdfLanguage;

  /**
   * Special mode used only by the automatic expiration archive.
   *
   * Normal/manual PDF generation:
   * expirationArchive = false
   *
   * Automatic account-expiration archive:
   * expirationArchive = true
   *
   * In expiration mode, an attempt that was not completely
   * graded by the teacher must never receive an invented
   * development score or final score.
   */
  expirationArchive?:
    boolean;
};

/* =========================================================
   Translations
   ========================================================= */

const translations = {
  en: {
    documentTitle:
      "Quiz Correction",

    student:
      "Student",

    email:
      "Email",

    quiz:
      "Quiz",

    status:
      "Status",

    submittedAt:
      "Submitted",

    gradedAt:
      "Graded",

    automaticScore:
      "Automatic score",

    manualScore:
      "Manual score",

    finalScore:
      "Final score",

    percentage:
      "Percentage",

    question:
      "Question",

    points:
      "points",

    point:
      "point",

    qcm:
      "QCM",

    multipleChoice:
      "Multiple choice",

    development:
      "Development",

    studentAnswer:
      "Student answer",

    correctAnswer:
      "Correct answer",

    correctAnswers:
      "Correct answers",

    automaticGrade:
      "Automatic grade",

    teacherGrade:
      "Teacher grade",

    noAnswer:
      "No answer provided",

    selected:
      "Selected",

    correct:
      "Correct",

    wrong:
      "Incorrect",

    score:
      "Score",

    correction:
      "Correction",

    generatedBy:
      "Generated by ULearn",

    page:
      "Page",

    of:
      "of",

    graded:
      "Graded",

    submitted:
      "Waiting for correction",

    inProgress:
      "In progress",

    notGraded:
      "Not graded",

    notAvailable:
      "Not available",
  },

  fr: {
    documentTitle:
      "Correction du quiz",

    student:
      "Étudiant",

    email:
      "Adresse courriel",

    quiz:
      "Quiz",

    status:
      "Statut",

    submittedAt:
      "Soumis le",

    gradedAt:
      "Corrigé le",

    automaticScore:
      "Note automatique",

    manualScore:
      "Note manuelle",

    finalScore:
      "Note finale",

    percentage:
      "Pourcentage",

    question:
      "Question",

    points:
      "points",

    point:
      "point",

    qcm:
      "QCM",

    multipleChoice:
      "Réponses multiples",

    development:
      "Développement",

    studentAnswer:
      "Réponse de l’étudiant",

    correctAnswer:
      "Bonne réponse",

    correctAnswers:
      "Bonnes réponses",

    automaticGrade:
      "Note automatique",

    teacherGrade:
      "Note de l’enseignant",

    noAnswer:
      "Aucune réponse fournie",

    selected:
      "Sélectionnée",

    correct:
      "Bonne réponse",

    wrong:
      "Incorrecte",

    score:
      "Note",

    correction:
      "Correction",

    generatedBy:
      "Généré par ULearn",

    page:
      "Page",

    of:
      "sur",

    graded:
      "Corrigé",

    submitted:
      "En attente de correction",

    inProgress:
      "En cours",

    notGraded:
      "Non corrigé",

    notAvailable:
      "Non disponible",
  },

  rn: {
    documentTitle:
      "Ikosorwa rya quiz",

    student:
      "Umunyeshure",

    email:
      "Email",

    quiz:
      "Quiz",

    status:
      "Uko ihagaze",

    submittedAt:
      "Yatanzwe",

    gradedAt:
      "Yakosowe",

    automaticScore:
      "Amanota yikora",

    manualScore:
      "Amanota yatanzwe n’umwigisha",

    finalScore:
      "Amanota ya nyuma",

    percentage:
      "Ijanisha",

    question:
      "Ikibazo",

    points:
      "amanota",

    point:
      "inota",

    qcm:
      "QCM",

    multipleChoice:
      "Inyishu nyinshi",

    development:
      "Ikibazo gisaba insiguro",

    studentAnswer:
      "Inyishu y’umunyeshure",

    correctAnswer:
      "Inyishu nziza",

    correctAnswers:
      "Inyishu nziza",

    automaticGrade:
      "Amanota yikora",

    teacherGrade:
      "Amanota y’umwigisha",

    noAnswer:
      "Nta nyishu yatanzwe",

    selected:
      "Yahisemwo",

    correct:
      "Ni yo",

    wrong:
      "Si yo",

    score:
      "Amanota",

    correction:
      "Ikosorwa",

    generatedBy:
      "Yakozwe na ULearn",

    page:
      "Urupapuro",

    of:
      "kuri",

    graded:
      "Yakosowe",

    submitted:
      "Irindiriye gukosorwa",

    inProgress:
      "Iriko irakorwa",

    notGraded:
      "Ntikirakosorwa",

    notAvailable:
      "Ntiboneka",
  },
} as const;

/* =========================================================
   Colors
   ========================================================= */

const COLORS = {
  primary:
    "#2a0369",

  primarySoft:
    "#f2eef8",

  primaryLight:
    "#faf8fd",

  text:
    "#171717",

  muted:
    "#66616d",

  border:
    "#ddd4e9",

  success:
    "#17683d",

  successBackground:
    "#eef8f2",

  danger:
    "#9c1c31",

  dangerBackground:
    "#fdf0f2",

  white:
    "#ffffff",
};

/* =========================================================
   Styles
   ========================================================= */

const styles =
  StyleSheet.create({
    page: {
      paddingTop:
        38,

      paddingRight:
        38,

      paddingBottom:
        52,

      paddingLeft:
        38,

      backgroundColor:
        COLORS.white,

      color:
        COLORS.text,

      fontSize:
        9,

      fontFamily:
        "Helvetica",
    },

    header: {
      marginBottom:
        20,

      paddingBottom:
        16,

      borderBottomWidth:
        1,

      borderBottomColor:
        COLORS.border,

      borderBottomStyle:
        "solid",
    },

    brandRow: {
      display:
        "flex",

      flexDirection:
        "row",

      alignItems:
        "center",

      justifyContent:
        "space-between",

      marginBottom:
        14,
    },

    brand: {
      fontSize:
        20,

      fontWeight:
        700,

      color:
        COLORS.primary,
    },

    documentBadge: {
      paddingVertical:
        5,

      paddingHorizontal:
        9,

      borderRadius:
        20,

      backgroundColor:
        COLORS.primarySoft,

      color:
        COLORS.primary,

      fontSize:
        8,

      fontWeight:
        700,
    },

    title: {
      marginBottom:
        5,

      fontSize:
        24,

      fontWeight:
        700,

      color:
        COLORS.primary,
    },

    quizTitle: {
      fontSize:
        11,

      color:
        COLORS.muted,
    },

    section: {
      marginBottom:
        17,
    },

    sectionTitle: {
      marginBottom:
        8,

      fontSize:
        12,

      fontWeight:
        700,

      color:
        COLORS.primary,
    },

    studentCard: {
      padding:
        12,

      borderWidth:
        1,

      borderColor:
        COLORS.border,

      borderStyle:
        "solid",

      borderRadius:
        7,

      backgroundColor:
        COLORS.primaryLight,
    },

    studentName: {
      marginBottom:
        4,

      fontSize:
        12,

      fontWeight:
        700,

      color:
        COLORS.primary,
    },

    studentEmail: {
      fontSize:
        8.5,

      color:
        COLORS.muted,
    },

    metadataGrid: {
      display:
        "flex",

      flexDirection:
        "row",

      flexWrap:
        "wrap",

      gap:
        7,

      marginTop:
        9,
    },

    metadataItem: {
      width:
        "48%",

      padding:
        8,

      borderWidth:
        1,

      borderColor:
        COLORS.border,

      borderStyle:
        "solid",

      borderRadius:
        5,

      backgroundColor:
        COLORS.white,
    },

    metadataLabel: {
      marginBottom:
        3,

      fontSize:
        7,

      color:
        COLORS.muted,
    },

    metadataValue: {
      fontSize:
        8.5,

      fontWeight:
        700,

      color:
        COLORS.primary,
    },

    scoreGrid: {
      display:
        "flex",

      flexDirection:
        "row",

      gap:
        7,
    },

    scoreCard: {
      flexGrow:
        1,

      flexBasis:
        0,

      padding:
        10,

      borderWidth:
        1,

      borderColor:
        COLORS.border,

      borderStyle:
        "solid",

      borderRadius:
        6,

      backgroundColor:
        COLORS.primaryLight,
    },

    finalScoreCard: {
      flexGrow:
        1,

      flexBasis:
        0,

      padding:
        10,

      borderRadius:
        6,

      backgroundColor:
        COLORS.primary,
    },

    scoreLabel: {
      marginBottom:
        4,

      fontSize:
        7,

      color:
        COLORS.muted,
    },

    scoreValue: {
      fontSize:
        13,

      fontWeight:
        700,

      color:
        COLORS.primary,
    },

    finalScoreLabel: {
      marginBottom:
        4,

      fontSize:
        7,

      color:
        "#e8ddf5",
    },

    finalScoreValue: {
      fontSize:
        13,

      fontWeight:
        700,

      color:
        COLORS.white,
    },

    questionCard: {
      marginBottom:
        12,

      padding:
        12,

      borderWidth:
        1,

      borderColor:
        COLORS.border,

      borderStyle:
        "solid",

      borderRadius:
        7,

      backgroundColor:
        COLORS.white,
    },

    questionTop: {
      display:
        "flex",

      flexDirection:
        "row",

      justifyContent:
        "space-between",

      alignItems:
        "flex-start",

      gap:
        10,

      marginBottom:
        8,
    },

    questionHeading: {
      flexGrow:
        1,

      flexBasis:
        0,
    },

    questionNumber: {
      marginBottom:
        4,

      fontSize:
        7,

      fontWeight:
        700,

      color:
        COLORS.muted,
    },

    questionText: {
      fontSize:
        11,

      fontWeight:
        700,

      color:
        COLORS.primary,

      lineHeight:
        1.35,
    },

    pointsBadge: {
      paddingVertical:
        4,

      paddingHorizontal:
        7,

      borderRadius:
        15,

      backgroundColor:
        COLORS.primarySoft,

      color:
        COLORS.primary,

      fontSize:
        7.5,

      fontWeight:
        700,
    },

    typeBadge: {
      alignSelf:
        "flex-start",

      marginBottom:
        9,

      paddingVertical:
        4,

      paddingHorizontal:
        7,

      borderRadius:
        14,

      backgroundColor:
        COLORS.primarySoft,

      color:
        COLORS.primary,

      fontSize:
        7,

      fontWeight:
        700,
    },

    choice: {
      display:
        "flex",

      flexDirection:
        "row",

      alignItems:
        "center",

      gap:
        7,

      marginBottom:
        5,

      padding:
        7,

      borderWidth:
        1,

      borderColor:
        COLORS.border,

      borderStyle:
        "solid",

      borderRadius:
        5,

      backgroundColor:
        COLORS.white,
    },

    correctChoice: {
      backgroundColor:
        COLORS.successBackground,

      borderColor:
        "#aed5bd",
    },

    wrongSelectedChoice: {
      backgroundColor:
        COLORS.dangerBackground,

      borderColor:
        "#e5b7bf",
    },

    choiceLetter: {
      width:
        20,

      height:
        20,

      display:
        "flex",

      alignItems:
        "center",

      justifyContent:
        "center",

      borderRadius:
        5,

      backgroundColor:
        COLORS.primarySoft,

      color:
        COLORS.primary,

      fontSize:
        7,

      fontWeight:
        700,
    },

    choiceText: {
      flexGrow:
        1,

      flexBasis:
        0,

      fontSize:
        8.5,

      lineHeight:
        1.4,
    },

    choiceLabels: {
      display:
        "flex",

      flexDirection:
        "row",

      gap:
        4,

      flexWrap:
        "wrap",
    },

    selectedLabel: {
      paddingVertical:
        2,

      paddingHorizontal:
        5,

      borderRadius:
        10,

      backgroundColor:
        COLORS.primarySoft,

      color:
        COLORS.primary,

      fontSize:
        6,
    },

    correctLabel: {
      paddingVertical:
        2,

      paddingHorizontal:
        5,

      borderRadius:
        10,

      backgroundColor:
        COLORS.success,

      color:
        COLORS.white,

      fontSize:
        6,
    },

    wrongLabel: {
      paddingVertical:
        2,

      paddingHorizontal:
        5,

      borderRadius:
        10,

      backgroundColor:
        COLORS.danger,

      color:
        COLORS.white,

      fontSize:
        6,
    },

    answerTitle: {
      marginBottom:
        5,

      fontSize:
        7,

      fontWeight:
        700,

      color:
        COLORS.muted,
    },

    developmentAnswer: {
      minHeight:
        55,

      marginBottom:
        8,

      padding:
        9,

      borderWidth:
        1,

      borderColor:
        COLORS.border,

      borderStyle:
        "solid",

      borderRadius:
        5,

      backgroundColor:
        COLORS.primaryLight,

      fontSize:
        8.5,

      lineHeight:
        1.5,
    },

    noAnswer: {
      marginBottom:
        8,

      padding:
        9,

      borderWidth:
        1,

      borderColor:
        COLORS.border,

      borderStyle:
        "dashed",

      borderRadius:
        5,

      color:
        COLORS.muted,

      fontSize:
        8,

      fontStyle:
        "italic",
    },

    gradeRow: {
      display:
        "flex",

      flexDirection:
        "row",

      alignItems:
        "center",

      justifyContent:
        "space-between",

      marginTop:
        8,

      padding:
        8,

      borderRadius:
        5,

      backgroundColor:
        COLORS.primarySoft,
    },

    gradeLabel: {
      fontSize:
        7.5,

      color:
        COLORS.muted,
    },

    gradeValue: {
      fontSize:
        9,

      fontWeight:
        700,

      color:
        COLORS.primary,
    },

    footer: {
      position:
        "absolute",

      left:
        38,

      right:
        38,

      bottom:
        22,

      display:
        "flex",

      flexDirection:
        "row",

      justifyContent:
        "space-between",

      paddingTop:
        7,

      borderTopWidth:
        1,

      borderTopColor:
        COLORS.border,

      borderTopStyle:
        "solid",
    },

    footerText: {
      fontSize:
        6.5,

      color:
        COLORS.muted,
    },
  });

/* =========================================================
   Helpers
   ========================================================= */

function roundScore(
  value: number
) {
  return (
    Math.round(
      (
        value +
        Number.EPSILON
      ) *
        10000
    ) /
    10000
  );
}

function getChoiceLetter(
  displayedIndex:
    number
) {
  return String.fromCharCode(
    65 +
      displayedIndex
  );
}

function getStatusLabel(
  attempt:
    Attempt,
  labels:
    typeof translations.en
) {
  if (
    attempt.status ===
    "graded"
  ) {
    return labels.graded;
  }

  if (
    attempt.status ===
    "submitted"
  ) {
    return labels.submitted;
  }

  return labels.inProgress;
}

function formatDate(
  value:
    string | null,
  language:
    PdfLanguage
) {
  if (
    !value
  ) {
    return "—";
  }

  const date =
    new Date(
      value
    );

  if (
    Number.isNaN(
      date.getTime()
    )
  ) {
    return "—";
  }

  const locale =
    language ===
    "fr"
      ? "fr-CA"
      : language ===
          "rn"
        ? "rn-BI"
        : "en-CA";

  try {
    return date.toLocaleString(
      locale,
      {
        year:
          "numeric",

        month:
          "short",

        day:
          "2-digit",

        hour:
          "2-digit",

        minute:
          "2-digit",
      }
    );
  } catch {
    return date.toLocaleString(
      "en-CA"
    );
  }
}

/* =========================================================
   Question score
   ========================================================= */

function calculateAutomaticQuestionScore(
  question:
    Question,
  answer:
    AttemptAnswer | undefined
) {
  if (
    question.type ===
    "development"
  ) {
    return 0;
  }

  if (
    question.type ===
    "qcm"
  ) {
    return answer
      ?.selectedChoiceIndex ===
      question.correctChoiceIndex
      ? question.points
      : 0;
  }

  const selected =
    Array.isArray(
      answer
        ?.selectedChoiceIndexes
    )
      ? [
          ...new Set(
            answer
              .selectedChoiceIndexes
          ),
        ]
      : [];

  const correct = [
    ...new Set(
      question
        .correctChoiceIndexes
    ),
  ];

  if (
    correct.length ===
    0 ||
    selected.length ===
    0
  ) {
    return 0;
  }

  const correctSet =
    new Set(
      correct
    );

  let correctlySelected =
    0;

  let incorrectlySelected =
    0;

  for (
    const index of
    selected
  ) {
    if (
      correctSet.has(
        index
      )
    ) {
      correctlySelected +=
        1;
    } else {
      incorrectlySelected +=
        1;
    }
  }

  const pointValue =
    question.points /
    correct.length;

  return roundScore(
    Math.max(
      0,
      Math.min(
        question.points,
        correctlySelected *
          pointValue -
          incorrectlySelected *
            pointValue
      )
    )
  );
}

/* =========================================================
   Component
   ========================================================= */

export default function AttemptCorrectionPdf({
  quiz,
  attempt,
  questions,
  language = "en",
  expirationArchive = false,
}: AttemptCorrectionPdfProps) {
  const safeLanguage:
    PdfLanguage =
    language === "fr" ||
    language === "rn"
      ? language
      : "en";

  const labels =
    translations[
      safeLanguage
    ];

  /*
   * This special behaviour is allowed only for the
   * automatic archive generated after account expiration.
   *
   * A graded attempt always keeps its normal correction,
   * even when it is included in the expiration archive.
   */
  const isIncompleteExpirationCorrection =
    expirationArchive &&
    attempt.status !==
      "graded";

  /* =====================================================
     Restore frozen question order
     ===================================================== */

  const questionMap =
    new Map(
      questions.map(
        (
          question
        ) => [
          question.id,
          question,
        ]
      )
    );

  const orderedQuestions =
    attempt.questionOrder
      .map(
        (
          questionId
        ) =>
          questionMap.get(
            questionId
          )
      )
      .filter(
        (
          question
        ): question is Question =>
          Boolean(
            question
          )
      );

  /* =====================================================
     Scores
     ===================================================== */

  const automaticScore =
    roundScore(
      orderedQuestions.reduce(
        (
          total,
          question
        ) =>
          total +
          calculateAutomaticQuestionScore(
            question,
            attempt.answers[
              question.id
            ]
          ),
        0
      )
    );

  /*
   * This numeric value remains useful for fully graded
   * attempts.
   *
   * For an incomplete expiration archive we deliberately
   * do NOT use it to manufacture a final score.
   */
  const manualScore =
    roundScore(
      orderedQuestions.reduce(
        (
          total,
          question
        ) => {
          if (
            question.type !==
            "development"
          ) {
            return total;
          }

          return (
            total +
            (
              attempt
                .developmentScores[
                question.id
              ] ??
              0
            )
          );
        },
        0
      )
    );

  /*
   * Normal/manual PDFs preserve the previous behaviour.
   *
   * In an expiration archive, however, an ungraded copy
   * has no legitimate final score because development
   * questions may still require teacher grading.
   */
  const finalScore =
    isIncompleteExpirationCorrection
      ? null
      : attempt.finalScore ??
        roundScore(
          automaticScore +
            manualScore
        );

  const percentage =
    finalScore !== null &&
    quiz.totalPoints > 0
      ? Math.round(
          (
            finalScore /
            quiz.totalPoints
          ) *
            100
        )
      : null;

  /* =====================================================
     PDF
     ===================================================== */

  return (
    <Document
      title={`${labels.documentTitle} - ${quiz.title}`}
      author="ULearn"
      subject={
        labels.documentTitle
      }
      creator="ULearn"
    >
      <Page
        size="A4"
        style={
          styles.page
        }
        wrap
      >
        {/* =================================================
            Header
            ================================================= */}

        <View
          style={
            styles.header
          }
        >
          <View
            style={
              styles.brandRow
            }
          >
            <Text
              style={
                styles.brand
              }
            >
              ULearn
            </Text>

            <Text
              style={
                styles.documentBadge
              }
            >
              {
                labels.correction
              }
            </Text>
          </View>

          <Text
            style={
              styles.title
            }
          >
            {
              labels.documentTitle
            }
          </Text>

          <Text
            style={
              styles.quizTitle
            }
          >
            {labels.quiz}:{" "}
            {quiz.title}
          </Text>
        </View>

        {/* =================================================
            Student
            ================================================= */}

        <View
          style={
            styles.section
          }
        >
          <Text
            style={
              styles.sectionTitle
            }
          >
            {
              labels.student
            }
          </Text>

          <View
            style={
              styles.studentCard
            }
          >
            <Text
              style={
                styles.studentName
              }
            >
              {
                attempt.studentName
              }
            </Text>

            <Text
              style={
                styles.studentEmail
              }
            >
              {labels.email}:{" "}
              {
                attempt.studentEmail
              }
            </Text>

            <View
              style={
                styles.metadataGrid
              }
            >
              <View
                style={
                  styles.metadataItem
                }
              >
                <Text
                  style={
                    styles.metadataLabel
                  }
                >
                  {
                    labels.status
                  }
                </Text>

                <Text
                  style={
                    styles.metadataValue
                  }
                >
                  {getStatusLabel(
                    attempt,
                    labels
                  )}
                </Text>
              </View>

              <View
                style={
                  styles.metadataItem
                }
              >
                <Text
                  style={
                    styles.metadataLabel
                  }
                >
                  {
                    labels.submittedAt
                  }
                </Text>

                <Text
                  style={
                    styles.metadataValue
                  }
                >
                  {formatDate(
                    attempt.submittedAt,
                    safeLanguage
                  )}
                </Text>
              </View>

              <View
                style={
                  styles.metadataItem
                }
              >
                <Text
                  style={
                    styles.metadataLabel
                  }
                >
                  {
                    labels.gradedAt
                  }
                </Text>

                <Text
                  style={
                    styles.metadataValue
                  }
                >
                  {formatDate(
                    attempt.gradedAt,
                    safeLanguage
                  )}
                </Text>
              </View>

              <View
                style={
                  styles.metadataItem
                }
              >
                <Text
                  style={
                    styles.metadataLabel
                  }
                >
                  {
                    labels.quiz
                  }
                </Text>

                <Text
                  style={
                    styles.metadataValue
                  }
                >
                  {
                    quiz.title
                  }
                </Text>
              </View>
            </View>
          </View>
        </View>

        {/* =================================================
            Score summary
            ================================================= */}

        <View
          style={
            styles.section
          }
        >
          <Text
            style={
              styles.sectionTitle
            }
          >
            {
              labels.score
            }
          </Text>

          <View
            style={
              styles.scoreGrid
            }
          >
            <View
              style={
                styles.scoreCard
              }
            >
              <Text
                style={
                  styles.scoreLabel
                }
              >
                {
                  labels.automaticScore
                }
              </Text>

              <Text
                style={
                  styles.scoreValue
                }
              >
                {
                  automaticScore
                }
              </Text>
            </View>

            <View
              style={
                styles.scoreCard
              }
            >
              <Text
                style={
                  styles.scoreLabel
                }
              >
                {
                  labels.manualScore
                }
              </Text>

              <Text
                style={
                  styles.scoreValue
                }
              >
                {isIncompleteExpirationCorrection
                  ? labels.notGraded
                  : manualScore}
              </Text>
            </View>

            <View
              style={
                styles.finalScoreCard
              }
            >
              <Text
                style={
                  styles.finalScoreLabel
                }
              >
                {
                  labels.finalScore
                }
              </Text>

              <Text
                style={
                  styles.finalScoreValue
                }
              >
                {finalScore ===
                null
                  ? labels.notAvailable
                  : `${finalScore} / ${quiz.totalPoints}`}
              </Text>
            </View>

            <View
              style={
                styles.scoreCard
              }
            >
              <Text
                style={
                  styles.scoreLabel
                }
              >
                {
                  labels.percentage
                }
              </Text>

              <Text
                style={
                  styles.scoreValue
                }
              >
                {percentage ===
                null
                  ? labels.notAvailable
                  : `${percentage}%`}
              </Text>
            </View>
          </View>
        </View>

        {/* =================================================
            Questions
            ================================================= */}

        <View>
          <Text
            style={
              styles.sectionTitle
            }
          >
            {
              labels.correction
            }
          </Text>

          {orderedQuestions.map(
            (
              question,
              questionIndex
            ) => {
              const answer =
                attempt.answers[
                  question.id
                ];

              /* ===========================================
                 Development
                 =========================================== */

              if (
                question.type ===
                "development"
              ) {
                const studentAnswer =
                  answer
                    ?.developmentAnswer
                    ?.trim() ||
                  "";

                /*
                 * We distinguish a real teacher score from
                 * an absent score.
                 *
                 * A real score of 0 remains 0.
                 * Missing is NOT converted to 0 in the
                 * expiration archive.
                 */
                const storedScore =
                  attempt
                    .developmentScores[
                    question.id
                  ];

                const hasTeacherScore =
                  typeof storedScore ===
                    "number" &&
                  Number.isFinite(
                    storedScore
                  );

                const score =
                  hasTeacherScore
                    ? storedScore
                    : 0;

                /*
                 * For a non-graded expiration copy, teacher
                 * grading is considered unfinished.
                 *
                 * We therefore display "Not graded" instead
                 * of interpreting a missing score as zero.
                 */
                const showDevelopmentAsNotGraded =
                  isIncompleteExpirationCorrection &&
                  !hasTeacherScore;

                return (
                  <View
                    key={
                      question.id
                    }
                    style={
                      styles.questionCard
                    }
                    wrap={false}
                  >
                    <View
                      style={
                        styles.questionTop
                      }
                    >
                      <View
                        style={
                          styles.questionHeading
                        }
                      >
                        <Text
                          style={
                            styles.questionNumber
                          }
                        >
                          {
                            labels.question
                          }{" "}
                          {
                            questionIndex +
                            1
                          }
                        </Text>

                        <Text
                          style={
                            styles.questionText
                          }
                        >
                          {
                            question.text
                          }
                        </Text>
                      </View>

                      <Text
                        style={
                          styles.pointsBadge
                        }
                      >
                        {showDevelopmentAsNotGraded
                          ? `${labels.notGraded} / ${question.points}`
                          : `${score} / ${question.points}`}
                      </Text>
                    </View>

                    <Text
                      style={
                        styles.typeBadge
                      }
                    >
                      {
                        labels.development
                      }
                    </Text>

                    <Text
                      style={
                        styles.answerTitle
                      }
                    >
                      {
                        labels.studentAnswer
                      }
                    </Text>

                    {studentAnswer ? (
                      <Text
                        style={
                          styles.developmentAnswer
                        }
                      >
                        {
                          studentAnswer
                        }
                      </Text>
                    ) : (
                      <Text
                        style={
                          styles.noAnswer
                        }
                      >
                        {
                          labels.noAnswer
                        }
                      </Text>
                    )}

                    <View
                      style={
                        styles.gradeRow
                      }
                    >
                      <Text
                        style={
                          styles.gradeLabel
                        }
                      >
                        {
                          labels.teacherGrade
                        }
                      </Text>

                      <Text
                        style={
                          styles.gradeValue
                        }
                      >
                        {showDevelopmentAsNotGraded
                          ? `${labels.notGraded} / ${question.points}`
                          : `${score} / ${question.points}`}
                      </Text>
                    </View>
                  </View>
                );
              }

              /* ===========================================
                 QCM / multiple choice
                 =========================================== */

              const selectedIndexes =
                question.type ===
                "qcm"
                  ? typeof answer
                      ?.selectedChoiceIndex ===
                    "number"
                    ? [
                        answer
                          .selectedChoiceIndex,
                      ]
                    : []
                  : Array.isArray(
                        answer
                          ?.selectedChoiceIndexes
                      )
                    ? answer
                        .selectedChoiceIndexes
                    : [];

              const correctIndexes =
                question.type ===
                "qcm"
                  ? [
                      question
                        .correctChoiceIndex,
                    ]
                  : question
                      .correctChoiceIndexes;

              const frozenOrder =
                attempt
                  .choiceOrders[
                  question.id
                ];

              const displayedIndexes =
                Array.isArray(
                  frozenOrder
                ) &&
                frozenOrder.length ===
                  question
                    .choices.length
                  ? frozenOrder
                  : question.choices.map(
                      (
                        _,
                        index
                      ) =>
                        index
                    );

              const automaticQuestionScore =
                calculateAutomaticQuestionScore(
                  question,
                  answer
                );

              return (
                <View
                  key={
                    question.id
                  }
                  style={
                    styles.questionCard
                  }
                  wrap={false}
                >
                  <View
                    style={
                      styles.questionTop
                    }
                  >
                    <View
                      style={
                        styles.questionHeading
                      }
                    >
                      <Text
                        style={
                          styles.questionNumber
                        }
                      >
                        {
                          labels.question
                        }{" "}
                        {
                          questionIndex +
                          1
                        }
                      </Text>

                      <Text
                        style={
                          styles.questionText
                        }
                      >
                        {
                          question.text
                        }
                        </Text>
                      </View>

                    <Text
                      style={
                        styles.pointsBadge
                      }
                    >
                      {
                        automaticQuestionScore
                      }
                      {" / "}
                      {
                        question.points
                      }
                    </Text>
                  </View>

                  <Text
                    style={
                      styles.typeBadge
                    }
                  >
                    {question.type ===
                    "qcm"
                      ? labels.qcm
                      : labels.multipleChoice}
                  </Text>

                  {displayedIndexes.map(
                    (
                      originalIndex,
                      displayedIndex
                    ) => {
                      const selected =
                        selectedIndexes.includes(
                          originalIndex
                        );

                      const correct =
                        correctIndexes.includes(
                          originalIndex
                        );

                      const wrongSelected =
                        selected &&
                        !correct;

                      const choiceStyle =
                        correct
                          ? [
                              styles.choice,
                              styles.correctChoice,
                            ]
                          : wrongSelected
                            ? [
                                styles.choice,
                                styles.wrongSelectedChoice,
                              ]
                            : styles.choice;

                      return (
                        <View
                          key={
                            originalIndex
                          }
                          style={
                            choiceStyle
                          }
                        >
                          <View
                            style={
                              styles.choiceLetter
                            }
                          >
                            <Text>
                              {getChoiceLetter(
                                displayedIndex
                              )}
                            </Text>
                          </View>

                          <Text
                            style={
                              styles.choiceText
                            }
                          >
                            {
                              question
                                .choices[
                                originalIndex
                              ]
                            }
                          </Text>

                          <View
                            style={
                              styles.choiceLabels
                            }
                          >
                            {selected && (
                              <Text
                                style={
                                  styles.selectedLabel
                                }
                              >
                                {
                                  labels.selected
                                }
                              </Text>
                            )}

                            {correct && (
                              <Text
                                style={
                                  styles.correctLabel
                                }
                              >
                                {
                                  labels.correct
                                }
                              </Text>
                            )}

                            {wrongSelected && (
                              <Text
                                style={
                                  styles.wrongLabel
                                }
                              >
                                {
                                  labels.wrong
                                }
                              </Text>
                            )}
                          </View>
                        </View>
                      );
                    }
                  )}

                  {selectedIndexes.length ===
                    0 && (
                    <Text
                      style={
                        styles.noAnswer
                      }
                    >
                      {
                        labels.noAnswer
                      }
                    </Text>
                  )}

                  <View
                    style={
                      styles.gradeRow
                    }
                  >
                    <Text
                      style={
                        styles.gradeLabel
                      }
                    >
                      {
                        labels.automaticGrade
                      }
                    </Text>

                    <Text
                      style={
                        styles.gradeValue
                      }
                    >
                      {
                        automaticQuestionScore
                      }
                      {" / "}
                      {
                        question.points
                      }
                    </Text>
                  </View>
                </View>
              );
            }
          )}
        </View>

        {/* =================================================
            Footer
            ================================================= */}

        <View
          style={
            styles.footer
          }
          fixed
        >
          <Text
            style={
              styles.footerText
            }
          >
            {
              labels.generatedBy
            }
          </Text>

          <Text
            style={
              styles.footerText
            }
            render={({
              pageNumber,
              totalPages,
            }) =>
              `${labels.page} ${pageNumber} ${labels.of} ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}